
name: Test and deploy

# Actions that will be executed when you push code currently none
on:
  push:
    branches:
      - master

# on:
#   pull_request:
#     types: [ closed ]
#     branches:
#       - master

jobs:
 build_android:
  #  if: startsWith(github.head_ref, 'release/') == true
   name: Build release artifacts
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: permission to gradlew
       run: chmod +x gradlew 
     - name: permission to gradlew
       run: rm -rf $GRADLE_HOME/caches/build-cache-*
     - name: permission to gradlew
       run: echo $GRADLE_HOME
     - name: Build release APK and AAB after test
       run: |
         ./gradlew assembleDebug
         ./gradlew bundleDebug 
     # - name: Sign APK
     #   uses: r0adkll/sign-android-release@v1
     #   # ID used to access action output
     #   id: sign_app
     #   with:
     #    releaseDirectory: app/build/outputs/apk/release
     #    signingKeyBase64: ${{ secrets.SIGNING_KEY }}
     #    alias: ${{ secrets.ALIAS }}
     #    keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
     #    keyPassword: ${{ secrets.KEY_PASSWORD }}  
     - name: Upload APK
       uses: actions/upload-artifact@v2
       with:
         name: app-debug.apk
         path: app/build/outputs/apk/debug/app-debug.apk
     - name: Upload AAB Bundle
       uses: actions/upload-artifact@v2
       with:
         name: app-debug.aab
         path: app/build/outputs/bundle/debug/app-debug.aab

 deploy-firebase:
   needs: [ build_android ]
   runs-on: ubuntu-latest
   steps:
     - uses: actions/download-artifact@master
       with:
         name: app-debug.apk
     - name: upload artifact to Firebase App Distribution
       uses: wzieba/Firebase-Distribution-Github-Action@v1
       with:
         appId: ${{secrets.FIREBASE_APP_ID}}
         token: ${{secrets.FIREBASE_TOKEN}}
         groups: QF
         file: /home/runner/work/testandroid/testandroid/app-debug.apk
         releaseNotes: Workflow ${{ github.run_number }}

